#!/bin/bash/

root -l -b -q ./d01_Spectpp.C
root -l -b -q ./d02_InclSpectpp_py.C
root -l -b -q ./d03_InclSpectDataPyRatio.C
root -l -b -q ./d04_ParRatio_pp.C
root -l -b -q ./d05_InclLKRatio_DataPy_pp.C
root -l -b -q ./d06_InclLKRatio_DataPyRaio_pp.C
root -l -b -q ./d07_JELKRatio_DataPy_pp.C
root -l -b -q ./d08_JELKRatio_DataPyRaio_pp.C
root -l -b -q ./d09_JEParRatio_DataPy_pp.C
root -l -b -q ./d10_SpectpPb_MB.C
root -l -b -q ./d11_InclSpectpPb.C
root -l -b -q ./d12_InclSpectRatiowCent.C
root -l -b -q ./d13_JESpectpPb.C
root -l -b -q ./d14_JESpectRatiowCent.C
root -l -b -q ./d15_ParRatio_pPb.C
root -l -b -q ./d16_JELKRatio_DataPy_pPb.C
root -l -b -q ./d17_LKDoubleRatio_pPb.C
root -l -b -q ./d18_PyDataDoubleRatio_LK_pPb.C
root -l -b -q ./d19_JE_XPRatio_DataPy_pPb.C
root -l -b -q ./d20_XKDoubleRatio_pPb.C
root -l -b -q ./d21_Spectpp_w3UE.C
root -l -b -q ./d22_Spectpp_woUE.C
root -l -b -q ./d23_JESpectpp_py.C
root -l -b -q ./d24_InclJELKRatio_DataPy_pp.C
root -l -b -q ./d25_SpectpPb_w3UE_MB.C
root -l -b -q ./d26_SpectpPb_woUE_MB.C
root -l -b -q ./d27_JESpectpPb_DataPy.C
root -l -b -q ./d28_JEParRatio_pp_pPb.C
root -l -b -q ./d29_JESpectDataPyRatio.C
